### ISSUE TITLE
FC01-03 彈窗

### ISSUE THREAD

**Issue by guitimliu** [rider159159/wowcho-ui#3]

**Comment by rider159159** [comment]
檔案: components/common/Modal.vue
開啟關閉彈窗，直接在 Modal 元件寫入 v-model 布林值做判斷。

有五個 props 選項可以寫入:

- title : 彈窗標題
- width : 彈窗寬度，直接輸入的是 class 樣式即可
- headerClass : Modal header 上的 class，直接輸入 class 樣式即可
- titleClass : 標題的 class，直接輸入 class 樣式即可
- bodyClass: Modal body 上的 class ，直接輸入 class 樣式即可

詳細操作、使用可參考 demo 頁面使用。

**Comment by rider159159** [comment]
此功能於 feat-commonComponents 分支上
